kind: Service
apiVersion: v1
metadata:
  namespace: nginx
  name: notes-app-service
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  
